name: suhaimiphotography
favicon: null
layout_spectrum: 0.26113
typography_spectrum: 0.66023
title: Suhaimi Abdullah
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060407'
    - '#fefefe'
    - '#3160ae'
    - '#6696de'
    - '#3d342b'
  brandStrength: 0
  lightness: 0.695784280076623
  saturation: 0.4375
  rhythmicContrast: 0.7184638786129653
purpose: []
